/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,ts,jsx,tsx,mdx}','./components/**/*.{js,ts,jsx,tsx,mdx}','./lib/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'ink-deep': '#1A1C1E',
        'ink': '#2D2F33',
        'ink-mid': '#4A4D52',
        'ink-soft': '#6B6F75',
        'ink-faint': '#8E9298',
        'paper': '#F2EFEA',
        'paper-light': '#F8F6F2',
        'paper-warm': '#EDE8E0',
        'paper-dark': '#E5DFD5',
        'jade': '#8BA8A0',
        'jade-light': '#A8C4BC',
        'jade-dark': '#6E8B83',
        'jade-pale': '#CBDCD6',
        'bronze': '#A0885A',
        'bronze-light': '#C4B08C',
        'bronze-dark': '#7D6A44',
        'bronze-pale': '#E0D4BE',
        'indigo': '#3B4252',
        'indigo-light': '#4F5A6E',
        'indigo-dark': '#2A3040',
        'indigo-pale': '#D5DAE4',
        'amber': '#C49A5E',
        'amber-light': '#D8B88A',
        'amber-dark': '#A37E48',
        'coral': '#C46A54',
        'coral-light': '#D48874',
        'coral-dark': '#A55440',
        'otb-terracotta': '#C46A54',
        'otb-ink': '#2D2F33',
        'otb-sand': '#E5DFD5',
      },
      fontFamily: {
        'sans': ['Inter', 'Noto Sans SC', 'system-ui', 'sans-serif'],
        'serif': ['Noto Serif SC', 'Georgia', 'serif'],
        'display': ['Playfair Display', 'Georgia', 'serif'],
        'en': ['Playfair Display', 'Georgia', 'serif'],
      },
      boxShadow: {
        'soft': '0 2px 20px rgba(26,28,30,0.04)',
        'soft-lg': '0 8px 40px rgba(26,28,30,0.05)',
        'elevated': '0 12px 48px rgba(26,28,30,0.07)',
        'inner-soft': 'inset 0 1px 0 rgba(255,255,255,0.4)',
        'card': '0 1px 3px rgba(26,28,30,0.04), 0 1px 2px rgba(26,28,30,0.02)',
      },
      backgroundImage: {
        'paper-texture': "url('/images/paper-texture.png')",
        'gradient-soft': 'linear-gradient(180deg, rgba(242,239,234,0) 0%, rgba(242,239,234,1) 100%)',
        'gradient-deep': 'linear-gradient(180deg, rgba(26,28,30,0) 0%, rgba(26,28,30,1) 100%)',
        'gradient-overlay': 'linear-gradient(to right, rgba(242,239,234,0.92) 0%, rgba(242,239,234,0) 50%)',
      },
      animation: {
        'fade-in': 'fadeIn 0.8s ease-out forwards',
        'fade-in-up': 'fadeInUp 0.6s ease-out forwards',
        'scale-in': 'scaleIn 0.4s ease-out forwards',
        'float': 'float 6s ease-in-out infinite',
        'drift': 'drift 20s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.97)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        drift: {
          '0%, 100%': { transform: 'translate(0, 0)' },
          '33%': { transform: 'translate(8px, -4px)' },
          '66%': { transform: 'translate(-4px, 6px)' },
        },
      },
    },
  },
  plugins: [],
}
